// Code generated by goctl. DO NOT EDIT.
// Source: UserServer.proto

package roleserver

import (
	"context"

	"github.com/zzp-Z/UserServer/user_server"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AddUserRoleRequest           = user_server.AddUserRoleRequest
	AddUserRoleResponse          = user_server.AddUserRoleResponse
	AuthenticateRequest          = user_server.AuthenticateRequest
	AuthenticateResponse         = user_server.AuthenticateResponse
	ChangePasswordRequest        = user_server.ChangePasswordRequest
	ChangePasswordResponse       = user_server.ChangePasswordResponse
	CheckUserRoleRequest         = user_server.CheckUserRoleRequest
	CheckUserRoleResponse        = user_server.CheckUserRoleResponse
	CreateRoleRequest            = user_server.CreateRoleRequest
	CreateRoleResponse           = user_server.CreateRoleResponse
	DeleteRoleRequest            = user_server.DeleteRoleRequest
	DeleteRoleResponse           = user_server.DeleteRoleResponse
	DeleteUserRequest            = user_server.DeleteUserRequest
	DeleteUserResponse           = user_server.DeleteUserResponse
	DeleteUserRoleRequest        = user_server.DeleteUserRoleRequest
	DeleteUserRoleResponse       = user_server.DeleteUserRoleResponse
	FollowRequest                = user_server.FollowRequest
	FollowResponse               = user_server.FollowResponse
	GetFollowersListRequest      = user_server.GetFollowersListRequest
	GetFollowersListResponse     = user_server.GetFollowersListResponse
	GetFollowingListRequest      = user_server.GetFollowingListRequest
	GetFollowingListResponse     = user_server.GetFollowingListResponse
	GetRoleListRequest           = user_server.GetRoleListRequest
	GetRoleListResponse          = user_server.GetRoleListResponse
	GetRoleRequest               = user_server.GetRoleRequest
	GetRoleResponse              = user_server.GetRoleResponse
	GetRoleUsersRequest          = user_server.GetRoleUsersRequest
	GetRoleUsersResponse         = user_server.GetRoleUsersResponse
	GetUserInfoByIdRequest       = user_server.GetUserInfoByIdRequest
	GetUserRolesRequest          = user_server.GetUserRolesRequest
	GetUserRolesResponse         = user_server.GetUserRolesResponse
	RegisterRequest              = user_server.RegisterRequest
	RegisterResponse             = user_server.RegisterResponse
	UnfollowRequest              = user_server.UnfollowRequest
	UnfollowResponse             = user_server.UnfollowResponse
	UpdateRoleRequest            = user_server.UpdateRoleRequest
	UpdateRoleResponse           = user_server.UpdateRoleResponse
	UpdateUserRequest            = user_server.UpdateUserRequest
	UpdateUserResponse           = user_server.UpdateUserResponse
	UserNonSensitiveInfoResponse = user_server.UserNonSensitiveInfoResponse
	UserSensitiveInfoResponse    = user_server.UserSensitiveInfoResponse

	RoleServer interface {
		// 获取角色信息
		GetRole(ctx context.Context, in *GetRoleRequest, opts ...grpc.CallOption) (*GetRoleResponse, error)
		// 获取角色列表
		GetRoleList(ctx context.Context, in *GetRoleListRequest, opts ...grpc.CallOption) (*GetRoleListResponse, error)
		// 更新角色
		UpdateRole(ctx context.Context, in *UpdateRoleRequest, opts ...grpc.CallOption) (*UpdateRoleResponse, error)
		// 删除角色
		DeleteRole(ctx context.Context, in *DeleteRoleRequest, opts ...grpc.CallOption) (*DeleteRoleResponse, error)
		// 创建角色
		CreateRole(ctx context.Context, in *CreateRoleRequest, opts ...grpc.CallOption) (*CreateRoleResponse, error)
	}

	defaultRoleServer struct {
		cli zrpc.Client
	}
)

func NewRoleServer(cli zrpc.Client) RoleServer {
	return &defaultRoleServer{
		cli: cli,
	}
}

// 获取角色信息
func (m *defaultRoleServer) GetRole(ctx context.Context, in *GetRoleRequest, opts ...grpc.CallOption) (*GetRoleResponse, error) {
	client := user_server.NewRoleServerClient(m.cli.Conn())
	return client.GetRole(ctx, in, opts...)
}

// 获取角色列表
func (m *defaultRoleServer) GetRoleList(ctx context.Context, in *GetRoleListRequest, opts ...grpc.CallOption) (*GetRoleListResponse, error) {
	client := user_server.NewRoleServerClient(m.cli.Conn())
	return client.GetRoleList(ctx, in, opts...)
}

// 更新角色
func (m *defaultRoleServer) UpdateRole(ctx context.Context, in *UpdateRoleRequest, opts ...grpc.CallOption) (*UpdateRoleResponse, error) {
	client := user_server.NewRoleServerClient(m.cli.Conn())
	return client.UpdateRole(ctx, in, opts...)
}

// 删除角色
func (m *defaultRoleServer) DeleteRole(ctx context.Context, in *DeleteRoleRequest, opts ...grpc.CallOption) (*DeleteRoleResponse, error) {
	client := user_server.NewRoleServerClient(m.cli.Conn())
	return client.DeleteRole(ctx, in, opts...)
}

// 创建角色
func (m *defaultRoleServer) CreateRole(ctx context.Context, in *CreateRoleRequest, opts ...grpc.CallOption) (*CreateRoleResponse, error) {
	client := user_server.NewRoleServerClient(m.cli.Conn())
	return client.CreateRole(ctx, in, opts...)
}
