// Code generated by goctl. DO NOT EDIT.
// Source: UserServer.proto

package server

import (
	"context"

	"github.com/zzp-Z/UserServer/internal/logic/userroleserver"
	"github.com/zzp-Z/UserServer/internal/svc"
	"github.com/zzp-Z/UserServer/user_server"
)

type UserRoleServerServer struct {
	svcCtx *svc.ServiceContext
	user_server.UnimplementedUserRoleServerServer
}

func NewUserRoleServerServer(svcCtx *svc.ServiceContext) *UserRoleServerServer {
	return &UserRoleServerServer{
		svcCtx: svcCtx,
	}
}

// 获取用户角色列表
func (s *UserRoleServerServer) GetUserRoles(ctx context.Context, in *user_server.GetUserRolesRequest) (*user_server.GetUserRolesResponse, error) {
	l := userroleserverlogic.NewGetUserRolesLogic(ctx, s.svcCtx)
	return l.GetUserRoles(in)
}

// 添加用户角色
func (s *UserRoleServerServer) AddUserRole(ctx context.Context, in *user_server.AddUserRoleRequest) (*user_server.AddUserRoleResponse, error) {
	l := userroleserverlogic.NewAddUserRoleLogic(ctx, s.svcCtx)
	return l.AddUserRole(in)
}

// 删除用户角色
func (s *UserRoleServerServer) DeleteUserRole(ctx context.Context, in *user_server.DeleteUserRoleRequest) (*user_server.DeleteUserRoleResponse, error) {
	l := userroleserverlogic.NewDeleteUserRoleLogic(ctx, s.svcCtx)
	return l.DeleteUserRole(in)
}

// 获取角色用户列表
func (s *UserRoleServerServer) GetRoleUsers(ctx context.Context, in *user_server.GetRoleUsersRequest) (*user_server.GetRoleUsersResponse, error) {
	l := userroleserverlogic.NewGetRoleUsersLogic(ctx, s.svcCtx)
	return l.GetRoleUsers(in)
}

// 检查用户角色
func (s *UserRoleServerServer) CheckUserRole(ctx context.Context, in *user_server.CheckUserRoleRequest) (*user_server.CheckUserRoleResponse, error) {
	l := userroleserverlogic.NewCheckUserRoleLogic(ctx, s.svcCtx)
	return l.CheckUserRole(in)
}
