// Code generated by goctl. DO NOT EDIT.
// Source: UserServer.proto

package userserver

import (
	"context"

	"github.com/zzp-Z/UserServer/user_server"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AddUserRoleRequest           = user_server.AddUserRoleRequest
	AddUserRoleResponse          = user_server.AddUserRoleResponse
	AuthenticateRequest          = user_server.AuthenticateRequest
	AuthenticateResponse         = user_server.AuthenticateResponse
	ChangePasswordRequest        = user_server.ChangePasswordRequest
	ChangePasswordResponse       = user_server.ChangePasswordResponse
	CheckUserRoleRequest         = user_server.CheckUserRoleRequest
	CheckUserRoleResponse        = user_server.CheckUserRoleResponse
	CreateRoleRequest            = user_server.CreateRoleRequest
	CreateRoleResponse           = user_server.CreateRoleResponse
	DeleteRoleRequest            = user_server.DeleteRoleRequest
	DeleteRoleResponse           = user_server.DeleteRoleResponse
	DeleteUserRequest            = user_server.DeleteUserRequest
	DeleteUserResponse           = user_server.DeleteUserResponse
	DeleteUserRoleRequest        = user_server.DeleteUserRoleRequest
	DeleteUserRoleResponse       = user_server.DeleteUserRoleResponse
	FollowRequest                = user_server.FollowRequest
	FollowResponse               = user_server.FollowResponse
	GetFollowersListRequest      = user_server.GetFollowersListRequest
	GetFollowersListResponse     = user_server.GetFollowersListResponse
	GetFollowingListRequest      = user_server.GetFollowingListRequest
	GetFollowingListResponse     = user_server.GetFollowingListResponse
	GetRoleListRequest           = user_server.GetRoleListRequest
	GetRoleListResponse          = user_server.GetRoleListResponse
	GetRoleRequest               = user_server.GetRoleRequest
	GetRoleResponse              = user_server.GetRoleResponse
	GetRoleUsersRequest          = user_server.GetRoleUsersRequest
	GetRoleUsersResponse         = user_server.GetRoleUsersResponse
	GetUserInfoByIdRequest       = user_server.GetUserInfoByIdRequest
	GetUserRolesRequest          = user_server.GetUserRolesRequest
	GetUserRolesResponse         = user_server.GetUserRolesResponse
	RegisterRequest              = user_server.RegisterRequest
	RegisterResponse             = user_server.RegisterResponse
	UnfollowRequest              = user_server.UnfollowRequest
	UnfollowResponse             = user_server.UnfollowResponse
	UpdateRoleRequest            = user_server.UpdateRoleRequest
	UpdateRoleResponse           = user_server.UpdateRoleResponse
	UpdateUserRequest            = user_server.UpdateUserRequest
	UpdateUserResponse           = user_server.UpdateUserResponse
	UserNonSensitiveInfoResponse = user_server.UserNonSensitiveInfoResponse
	UserSensitiveInfoResponse    = user_server.UserSensitiveInfoResponse

	UserServer interface {
		// 注册新用户
		Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
		// 验证用户密码（用途包括不限于“登录”，修改密码前的验证，修改信息前的验证等）
		Authenticate(ctx context.Context, in *AuthenticateRequest, opts ...grpc.CallOption) (*AuthenticateResponse, error)
		// 获取用户信息（包含敏感信息）
		GetUserSensitive(ctx context.Context, in *GetUserInfoByIdRequest, opts ...grpc.CallOption) (*UserSensitiveInfoResponse, error)
		// 获取用户信息（不包含敏感信息）
		GetUserNonSensitive(ctx context.Context, in *GetUserInfoByIdRequest, opts ...grpc.CallOption) (*UserNonSensitiveInfoResponse, error)
		// 更新用户信息
		UpdateUser(ctx context.Context, in *UpdateUserRequest, opts ...grpc.CallOption) (*UpdateUserResponse, error)
		// 修改密码
		ChangePassword(ctx context.Context, in *ChangePasswordRequest, opts ...grpc.CallOption) (*ChangePasswordResponse, error)
		// 删除用户
		DeleteUser(ctx context.Context, in *DeleteUserRequest, opts ...grpc.CallOption) (*DeleteUserResponse, error)
	}

	defaultUserServer struct {
		cli zrpc.Client
	}
)

func NewUserServer(cli zrpc.Client) UserServer {
	return &defaultUserServer{
		cli: cli,
	}
}

// 注册新用户
func (m *defaultUserServer) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	client := user_server.NewUserServerClient(m.cli.Conn())
	return client.Register(ctx, in, opts...)
}

// 验证用户密码（用途包括不限于“登录”，修改密码前的验证，修改信息前的验证等）
func (m *defaultUserServer) Authenticate(ctx context.Context, in *AuthenticateRequest, opts ...grpc.CallOption) (*AuthenticateResponse, error) {
	client := user_server.NewUserServerClient(m.cli.Conn())
	return client.Authenticate(ctx, in, opts...)
}

// 获取用户信息（包含敏感信息）
func (m *defaultUserServer) GetUserSensitive(ctx context.Context, in *GetUserInfoByIdRequest, opts ...grpc.CallOption) (*UserSensitiveInfoResponse, error) {
	client := user_server.NewUserServerClient(m.cli.Conn())
	return client.GetUserSensitive(ctx, in, opts...)
}

// 获取用户信息（不包含敏感信息）
func (m *defaultUserServer) GetUserNonSensitive(ctx context.Context, in *GetUserInfoByIdRequest, opts ...grpc.CallOption) (*UserNonSensitiveInfoResponse, error) {
	client := user_server.NewUserServerClient(m.cli.Conn())
	return client.GetUserNonSensitive(ctx, in, opts...)
}

// 更新用户信息
func (m *defaultUserServer) UpdateUser(ctx context.Context, in *UpdateUserRequest, opts ...grpc.CallOption) (*UpdateUserResponse, error) {
	client := user_server.NewUserServerClient(m.cli.Conn())
	return client.UpdateUser(ctx, in, opts...)
}

// 修改密码
func (m *defaultUserServer) ChangePassword(ctx context.Context, in *ChangePasswordRequest, opts ...grpc.CallOption) (*ChangePasswordResponse, error) {
	client := user_server.NewUserServerClient(m.cli.Conn())
	return client.ChangePassword(ctx, in, opts...)
}

// 删除用户
func (m *defaultUserServer) DeleteUser(ctx context.Context, in *DeleteUserRequest, opts ...grpc.CallOption) (*DeleteUserResponse, error) {
	client := user_server.NewUserServerClient(m.cli.Conn())
	return client.DeleteUser(ctx, in, opts...)
}
